config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  namespace :account do
    resources :groups
    resources :posts
  end
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :posts,dependent: :destroy
  # validates :title, :description, presence: true
  validates :title, :description, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
  has_many :group_relationships
  has_many :members, through: :group_relationships, source: :user
  scope :recentt, -> { order("created_at DESC")}
end

app/models/group_relationship.rb
class GroupRelationship < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  belongs_to :group, counter_cache: :posts_count
  scope :recent, -> { order("created_at DESC")}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups
  has_many :posts
  has_many :group_relationships
  has_many :participated_groups, through: :group_relationships, source: :group

  def is_member_of?(group)
    participated_groups.include?(group)
  end

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups.recentt
  end

end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.order("updated_at DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :update, :destroy]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]
  before_action :find_group, only: [ :edit, :update, :detroy]
  def index
    @groups = Group.all.recentt
  end

  def new
    @group = Group.new
  end

  def create
    # @group = Group.new(group_params)
    @group = current_user.groups.new(group_params)
    @group.user = current_user
    if @group.save
      current_user.join!(@group)
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    # @posts = @group.posts.order("created_at DESC")
    @posts = @group.posts.recent.paginate(page: params[:page], per_page: 5)
    
  end

  def edit
    # find_group_and_check_permission
    # @group = Group.find(params[:id])
    # if current_user != @group.user
    #   redirect_to root_path, alert: "You have no permission"
    # end
  end

  def update
    # find_group_and_check_permission
    # @group = Group.find(params[:id])
    # if current_user != @group.user
    #   redirect_to root_path, alert: "You have no permission"
    # end
    if @group.update(group_params)
      redirect_to groups_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    # find_group_and_check_permission
    # @group = Group.find(params[:id])
    # if current_user != @group.user
    #   redirect_to root_path, alert: "You have no permission"
    # end
    @group.destroy
    flash[:alert] = "Group deleted"
    redirect_to groups_path
    #redirect_to groups_path, alert: "Group deleted"
  end

  def join
    @group = Group.find(params[:id])

    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "Join this Group success"
    else
      flash[:warning] = "U are already in this Group!"
    end

    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])

    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = "U Quit this Group"
    else
      flash[:warning] = "你本來就不是這個群組的！ 退屁！"
    end

    redirect_to group_path(@group)
  end

  private

  def find_group
    # @group = Group.find(params[:id])
    @group = current_user.groups.find(params[:id])
  end

  def find_group_and_check_permission
    @group = Group.find(params[:id])
    if current_user != @group.user
      redirect_to groups_path, alert: "You have no permission!"
    end
  end

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! ,  only: [:new, :create]

  def new
    @group = Group.find(params[:group_id])
    @post = Post.new
  end

  def create
    @group = Group.find(params[:group_id])
    @post = Post.new(post_params)
    @post.group = @group
    @post.user = current_user
    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end

  end

  private
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "Goodmorning!"
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASS = {alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASS.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_group_description(group)
    simple_format(group.description)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
    <% user_facing_flashes.each do |key, value| %>
        <div class="alert alert-dismissible alert-<%= flash_class(key) %>">
          <button class="close" data-dismiss="alert" >x</button>
          <%= value %>
        </div>
    <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" syle= "margin-top:100px;">
  <p class="text-center">  Copyright @2017 Alpha Camp
  <br>Design by
  <a href="#" >Paul</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<div class="navbar navbar-default " role= "navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/groups" class="navbar-brand"> Todolist Group</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
            <% if !current_user %>
              <li><%= link_to("註冊", new_user_registration_path) %></li>
              <li><%= link_to("登入",new_user_session_path) %></li>
            <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hi, <%= current_user.name %>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to("My Group",account_groups_path) %></li>
                    <li><%= link_to("My Posts", account_posts_path) %></li>
                    <li class="divider">  </li>
                    <li> <%= link_to("Account Setting",edit_user_registration_path) %></li>
                    <li>  <%= link_to("Sign_out", destroy_user_session_path, method: :delete) %></li>
                  </ul>
                </li>
            <% end %>
        </li>
      </ul>
    </div>
  </div>

</div>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <!-- <% if @group.errors.any? %>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
        <li>  <%= msg %></li>
        <% end %>
      </ul>
  <% end %> -->
  <div class="form-group">
    <%= f.input :title , input_html:{class: "form-control"} %>
    <%= f.input :description, input_html:{ class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting....."} %>
<% end %>

app/views/groups/_group_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(group.title, group_path(group)) %></td>
  <!-- <td><%= simple_format(group.description) %></td> -->
  <td>  <%= render_group_description(group) %></td>
  <td> <%= group.user.email %></td>
  <td>
    <% if current_user && current_user == group.user %>
        <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default") %>
        <%= link_to("Delete", group_path(group), method: :delete, data: {confirm: "Are UUU sure?!!"}, class: "btn btn-sm btn-default") %>
    <% end %>
  </td>
</tr>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>  編輯討論板</h2>
  <hr>
  <%= render "form" %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
        <td>Creator</td>
      </tr>
    </thead>
    <tbody>
    <%= render :partial => "group_item", :collection => @groups, :as => :group %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2> 新增討論板</h2>
  <hr>
  <%= render "form" %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@group) %>
          <label  class="label label-success">U're  Group's member</label>
          <%= link_to("Quit this Group",quit_group_path(@group), method: :post, class: "btn btn-default") %>
      <% else %>
            <label  class="label label-warning">U're Not Group's memeber</label>
            <%= link_to("Join this Group", join_group_path(@group), method: :post, class: "btn btn-default") %>
      <% end %>
    </span>
    <%= link_to("Write a Post", new_group_post_path(@group), class: "btn btn-default pull-right") %>
    <% if current_user && current_user == @group.user %>
      <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right") %>
    <% end %>
  </div>
  <h2> <%= @group.title %></h2>
  <p> <%= @group.description %></p>
  <table class="table">
    <thead>
      <tr>
        <th>文章內容</th>
        <th>發表者</th>
        <th>發表時間</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
          <tr>
            <td><%= post.content %></td>
            <td><%= post.user.email %></td>
            <td><%= post.created_at %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails101</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render "common/navbar" %>
    <%= render "common/flashes" %>
    <%= yield %>
  </div>
  <%= render "common/footer" %>

</body>
</html>

app/views/posts/new.html.erb
<h2 class="text-center"> 新增文章</h2>
<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group, @post] do |f| %>
      <div class="form-gorup">
        <%= f.input :content, input_html: { class: "form-control"} %>
      </div>
      <div class="form-acitons">
        <%= f.submit "Submit", disable_with: "Submiting..", class: "btn btn-primary" %>
      </div>
  <% end %>

</div>

app/views/welcome/index.html.erb
<h1>  Welcome!!</h1>